# Generated by Django 5.2.1 on 2025-05-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='designer.state')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='designer.state')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='designer.state')),
            ],
        ),
        migrations.CreateModel(
            name='AbayaDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=50)),
                ('fabric', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('design_image', models.ImageField(upload_to='designs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.user')),
            ],
        ),
    ]
