# Generated by Django 5.2.1 on 2025-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_topicsearchbyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='description',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
